# Generated by Django 5.0.6 on 2024-05-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_alter_clientes_contato'),
        ('Estabelecimento', '0003_alter_estabelecimento_contato'),
        ('Servicos', '0002_alter_servicos_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentosPeloCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_selecionado', models.TimeField()),
                ('dia_selecionado', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estabelecimento.estabelecimento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicos.servicos')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentosPeloEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('contato', models.CharField(max_length=12)),
                ('horario_selecionado', models.TimeField()),
                ('dia_selecionado', models.DateField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estabelecimento.estabelecimento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicos.servicos')),
            ],
        ),
    ]
