# Generated by Django 5.0.6 on 2024-05-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estabelecimento', '0002_estabelecimento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localicazao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estabelecimento.estabelecimento')),
            ],
        ),
    ]
