# Generated by Django 5.0.6 on 2024-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
