# Generated by Django 5.0.6 on 2024-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='contato',
            field=models.CharField(max_length=12),
        ),
    ]
