# Generated by Django 5.0.6 on 2024-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10),
        ),
    ]
